INSERT INTO words  VALUES (1,'手机','мобильныйы телефон');
INSERT INTO words  VALUES (2,'水','вода');
INSERT INTO words  VALUES (3,'力','сила; энергия; мощь');
INSERT INTO words  VALUES (4,'火','огонь; пламя');
INSERT INTO lists VALUES (1, 'First List');
INSERT INTO lists VALUES (2, 'Second List');
INSERT INTO lists_words VALUES (1, 1);
INSERT INTO lists_words VALUES (1, 2);
INSERT INTO lists_words VALUES (1, 3);
INSERT INTO lists_words VALUES (2, 4);